'use client';
import {useEffect,useRef,useState} from 'react';
import {flushSync} from 'react-dom';
import {works,artUrl} from './works';
export default function Home(){
const[index,setIndex]=useState(0),[inside,setInside]=useState(false);const stage=useRef<HTMLDivElement>(null),track=useRef<HTMLDivElement>(null),bar=useRef<HTMLSpanElement>(null),card=useRef<HTMLElement>(null),jump=useRef<(i:number)=>void>(()=>{});
useEffect(()=>{let dispose=()=>{},dead=false;Promise.all([import('gsap'),import('gsap/ScrollTrigger'),import('lenis')]).then(([G,S,L])=>{if(dead)return;const gsap=G.gsap,ScrollTrigger=S.ScrollTrigger;gsap.registerPlugin(ScrollTrigger);const reduced=matchMedia('(prefers-reduced-motion: reduce)');let lenis:InstanceType<typeof L.default>|undefined;let raf:((t:number)=>void)|undefined;let requested=0,serial=0;let transition:{skipTransition:()=>void;finished:Promise<void>}|undefined;let fade:Animation|undefined;const cache=new Map<number,Promise<void>>();
const decode=(i:number)=>{if(i<0||i>9)return Promise.resolve();let p=cache.get(i);if(!p){p=new Promise<void>((resolve,reject)=>{const img=new Image();img.src=artUrl(i);img.decode().then(()=>resolve()).catch(reject)});cache.set(i,p);p.catch(()=>cache.delete(i))}return p};
const change=async(next:number)=>{if(next===requested)return;requested=next;const ticket=++serial;try{await decode(next)}catch{return}if(dead||ticket!==serial)return;transition?.skipTransition();fade?.cancel();const update=()=>{if(dead||ticket!==serial)return;flushSync(()=>setIndex(next));for(const key of cache.keys())if(key!==next&&key!==next+1)cache.delete(key);void decode(next+1).catch(()=>{})};
if(reduced.matches){update();return}if(document.startViewTransition){transition=document.startViewTransition(update);transition.finished.catch(()=>{});}else{const el=card.current;if(el){fade=el.animate([{opacity:1},{opacity:0}],{duration:140,fill:'forwards'});try{await fade.finished}catch{}if(dead||ticket!==serial)return;update();fade.cancel();fade=el.animate([{opacity:0},{opacity:1}],{duration:380,easing:'ease-out'})}else update()}};
const smooth=()=>{if(raf)gsap.ticker.remove(raf);lenis?.destroy();lenis=undefined;if(!reduced.matches){lenis=new L.default({duration:1.05,smoothWheel:true,syncTouch:false,anchors:true});lenis.on('scroll',ScrollTrigger.update);raf=t=>lenis?.raf(t*1000);gsap.ticker.add(raf);gsap.ticker.lagSmoothing(0)}};smooth();
const trigger=ScrollTrigger.create({trigger:track.current,pin:stage.current,start:'top top',end:()=>'+='+window.innerHeight*9,anticipatePin:1,invalidateOnRefresh:true,snap:reduced.matches?undefined:{snapTo:1/9,duration:{min:.25,max:.65},delay:.25,ease:'power2.inOut',inertia:false},onToggle:self=>setInside(self.isActive),onUpdate:self=>{if(bar.current)bar.current.style.transform=`scaleY(${self.progress})`;void change(Math.min(9,Math.max(0,Math.round(self.progress*9))))}});
jump.current=i=>{const y=trigger.start+(trigger.end-trigger.start)*(i/9);if(lenis)lenis.scrollTo(y,{duration:.9});else window.scrollTo({top:y,behavior:'instant'})};const preference=()=>{smooth();transition?.skipTransition();fade?.cancel();trigger.vars.snap=reduced.matches?undefined:{snapTo:1/9,duration:.4,delay:.25,inertia:false};ScrollTrigger.refresh()};reduced.addEventListener('change',preference);void decode(0).then(()=>decode(1)).catch(()=>{});ScrollTrigger.refresh();
dispose=()=>{serial++;transition?.skipTransition();fade?.cancel();reduced.removeEventListener('change',preference);if(raf)gsap.ticker.remove(raf);lenis?.destroy();trigger.kill();cache.clear()};});return()=>{dead=true;dispose()}},[]);
const work=works[index];return <><header><a className="brand" href="#">Noémie Aster<span>ATELIER DE PEINTURE</span></a><nav aria-label="Navigation principale"><a href="#serie">La série</a><a href="#atelier">L’atelier</a><a href="#contact">Écrire</a></nav></header><main><section className="hero"><div className="hero-copy"><p className="eyebrow">Atelier de peinture. Nantes.</p><h1>Noémie<br/><em>Aster</em></h1><p className="hero-line">Une série. Un scroll.<br/>Une seule œuvre à la fois.</p><a className="begin" href="#serie">Commencer <span aria-hidden="true">↓</span></a></div><figure className="hero-painting"><img src={artUrl(0)} alt="Sans titre (bol), huile sur toile" fetchPriority="high"/><figcaption>Pièces silencieuses</figcaption></figure><span className="hero-year">2024 — 2026</span></section>
<section id="serie" ref={track} className="series"><div ref={stage} className="stage" style={{'--art-accent':work.accent} as React.CSSProperties}><div className="stage-heading"><h2>Pièces silencieuses</h2><span>2024 — 2026</span></div><article ref={card} className="painting-scene" data-painting={index+1} aria-label={'Toile '+(index+1)+' sur 10'}><div className="painting-notes">{index===0&&<p className="series-intro">Dix toiles peintes sur deux ans, dans la même lumière d'atelier. Faites défiler.</p>}<span className="work-number">{String(index+1).padStart(2,'0')}</span><h3>N°{String(index+1).padStart(2,'0')} — Sans titre ({work.subject})</h3><p className="medium">Huile sur toile, {work.size}, {work.year}</p><blockquote>« {work.note} »</blockquote></div><figure className="painting-frame"><img src={artUrl(index)} alt={'N°'+String(index+1).padStart(2,'0')+' — Sans titre ('+work.subject+')'} decoding="async"/></figure></article><div className="stage-bottom"><span>PIÈCES SILENCIEUSES</span><span aria-live="polite">{String(index+1).padStart(2,'0')} / 10</span><a href="#atelier">L’atelier <span aria-hidden="true">↘</span></a></div></div><aside className={'progress '+(inside?'visible':'')} aria-label="Progression de la série" aria-hidden={!inside}><span className="progress-start">01</span><div className="progress-track"><span ref={bar}/>{works.map((w,i)=><button key={w.subject} tabIndex={inside?0:-1} onClick={()=>jump.current(i)} aria-label={'Aller à la toile '+(i+1)} aria-current={index===i?'step':undefined} style={{top:(i/9)*100+'%'}}/>)}</div><span className="progress-end">10</span></aside></section>
<section id="atelier" className="editorial atelier"><span className="section-label">L’ATELIER</span><div><h2>L'atelier</h2><p>Noémie Aster peint à Nantes, dans un atelier baigné de lumière naturelle. Formée aux Beaux-Arts, elle travaille lentement, une toile à la fois, jamais en série de production. Chaque pièce naît d'une observation précise : un objet, une lumière, un instant qu'elle a voulu retenir.</p></div></section>
<section id="technique" className="editorial technique"><span className="section-label">MATIÈRES & TECHNIQUE</span><div><h2>Comment elle peint</h2><p>Huile sur toile, principalement. Des glacis successifs, une palette volontairement restreinte : blancs cassés, noirs profonds, une touche de couleur par toile. Le temps de séchage fait partie du processus : certaines pièces prennent plusieurs mois.</p></div></section>
<section id="expositions" className="expositions"><span className="section-label">EXPOSITIONS</span><ul><li>2026 — Galerie Marin, Nantes (solo)</li><li>2024 — Salon de la Jeune Peinture, Paris (collective)</li><li>2023 — Diplôme, Beaux-Arts de Nantes</li></ul></section>
<section id="contact" className="contact"><h2>Prendre contact</h2><p>Pour une visite d'atelier, une acquisition, ou une question sur une œuvre.</p><a href="mailto:?subject=Atelier%20No%C3%A9mie%20Aster">Écrire à l'atelier <span aria-hidden="true">↗</span></a></section></main><footer>Concept créé par Megahana — marque fictive à des fins de démonstration.</footer></>}
